### ISSUE TITLE
mod放置位置错误

### ISSUE THREAD

**Issue by tonny1983** [middlewhite/NIMBYRails-ChineseLanguage#2]
如说明所言，`下载后解压缩至C:\Users<您的用户名>\Saved Games\Weird and Wry\NIMBY Rails\mods文件夹下`。但实际上，路径应为`C:\Users\<您的用户名>\Saved Games\Weird and Wry\NIMBY Rails\mods\<任意新建的目录>`文件夹下。直接将txt和po文件放置于`mods`目录下将无法生效。

**Comment by middlewhite** [comment]
我使用的bandizip会在解压时自动新建文件夹，因此之前一直没有注意到这个问题，
以后会在上传的压缩包里直接新建好文件夹

**Comment by tonny1983** [comment]
在`README.md`中添加一下说明就行，我发现已经有人在别的地方问为什么文件放到`mods`目录下但是不生效了。
